### ISSUE TITLE
Asset store release RC1 quality

### ISSUE THREAD

**Issue by JamesMcGhee** [Unity-Technologies/GenericFrameRecorder#26]
I have tested a number of recordings of a simple 60second scene with a few objects 2 cameras (main and background) and a number of different recorder settings around mp4. In all cases the quality is unusable not intierly sure what is happening but the resulting video is very distorted as if massivly downscaled then scaled back up.

For note I am testing the case where 2 cameras are required to produce the final image so am recording from game view, I expect this will be a common case for most users and a common approch to capture the video (e.g. capture the game view not each camera indapendently then layer them as this would produce incorrect results in many cases)

I do wonder if capturing the game view considering the game view generally scales the output down to fit the box is the problem. Either way for this to be a time saver it should be able to capture the resulting render of any combination of cameras just as Game View would and it should be able to do so at any given resolution otherwise its simpliy easier and faster to compile, run and capture from the video card its self where you know the results are what you see.

**Comment by jasonm-unity** [comment]
have you boosted the output / bitrate? the default bitrate is just a number and should very much be tailored to the output resolution.

**Comment by JamesMcGhee** [comment]
Nope I didn't even think to expand the Encoding option.
So feature request, offer presets and calculated values similar what tools like Adobe Media Encoder do ... I will re-test using the values from Media Encoder to see how this works out.
I would expect most of us general users wont think of Encoding the first time they try it and when they do realise they like me wont really know what values would be good here so defently need at least some guidance on these values.

I'll reply again once I have tested using values I come up with off Media Encoder

**Comment by jasonm-unity** [comment]
Excellent feed back!

- For the bitrate, yup you are correct and that is in pipe as it definitely needs to be addressed. 
- The RunInBackground is in the feature request list.
- Switching recorders + carrying over settings, good point. it's an easy feature and I can see it being a friction point.
- For the tag part, since the resulting string can be edited, it was deemed better to just append and let user re-arrange as they like. The tag drop down was mainly for discovery of what tags are supported. 
 I personally never use the drop down as it's quicker to just right them out (once you know them of course)
